FROM python:3.12-slim

# Do not generate .pyc files and enable stdout buffering
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY backend/requirements.txt /app/requirements.txt

RUN pip install --upgrade pip && \
    pip install -r requirements.txt


COPY backend/ /app
COPY src/ /app/src
COPY vectorstores/ /app/vectorstores
# Create directories for PDF vectorstores
RUN mkdir -p /app/vectorstores/pdf_vectorstores

EXPOSE 8000

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]